# Generated by Django 3.0.6 on 2020-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O-', 'O Negative'), ('O+', 'O Positive'), ('A-', 'A Negative'), ('A+', 'A Positive'), ('B-', 'B Negative'), ('B+', 'B Positive'), ('AB-', 'ABNegative'), ('AB+', 'AB Positive')], default='O-', max_length=3)),
            ],
        ),
    ]
